name: Ansible Playbook
on: [push]

jobs:
  ansible_playbook_job:
    runs-on: ubuntu-latest
    name: Test this Action with a sample playbook
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Execute Ansible Playbook
        id: Execution
        uses: alfameCom/ansible-playbook-docker-action@master
        env:
          ANSIBLE_STDOUT_CALLBACK: debug
          ANSIBLE_FORCE_COLOR: true
        with:
          playbookName: ".ansible/playbooks/sample-playbook.yml"
          inventoryFile: ".ansible/inventory/local.yml"
          rolesPath: ".ansible/playbooks/roles"
          verbosity: "vvv"
